const data = {
  products: [
    {
      _id:'1',
      name: ' Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: '120',
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality shirts',
    },
    {
      _id:'2',
      name: ' Adidas fit shirt',
      slug: 'adidS-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: '250',
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'High Quality shirts',
    },
    {
      _id:'3',
      name: ' Nike slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: '125',
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'High Quality Pants',
    },
    {
      _id:'4',
      name: ' Adidas fit shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: '100',
      countInStock: 5,
      brand: 'puma',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality shirts',
    },
  ],
};
export default data;
